language: node_js
sudo: false
node_js:
  - "node"
before_install:
  - cd demo-code/balloons-game/
install:
  - npm install
script:
  - npm test
  - npm start &
  - sleep 20
  - pkill node
cache:
  directories:
    - "node_modules"
